[2023-05-10 03:55:48,403] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_processing_dag.download_dataset manual__2023-05-09T06:21:48.264367+00:00 [queued]>
[2023-05-10 03:55:48,451] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_processing_dag.download_dataset manual__2023-05-09T06:21:48.264367+00:00 [queued]>
[2023-05-10 03:55:48,451] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 03:55:48,452] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-05-10 03:55:48,457] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 03:55:48,500] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset> on 2023-05-09 06:21:48.287385+00:00
[2023-05-10 03:55:48,537] {standard_task_runner.py:52} INFO - Started process 1206 to run task
[2023-05-10 03:55:48,561] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_processing_dag', 'download_dataset', 'manual__2023-05-09T06:21:48.264367+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/data_processing_dag.py', '--cfg-path', '/tmp/tmpt4930zm1', '--error-file', '/tmp/tmp_7zfs8vd']
[2023-05-10 03:55:48,562] {standard_task_runner.py:77} INFO - Job 116: Subtask download_dataset
[2023-05-10 03:55:48,869] {logging_mixin.py:109} INFO - Running <TaskInstance: data_processing_dag.download_dataset manual__2023-05-09T06:21:48.264367+00:00 [running]> on host cd79de2e36bd
[2023-05-10 03:55:49,060] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_processing_dag
AIRFLOW_CTX_TASK_ID=download_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-05-09T06:21:48.287385+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-09T06:21:48.264367+00:00
[2023-05-10 03:55:49,065] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-10 03:55:49,073] {subprocess.py:74} INFO - Running command: ['bash', '-c', '#!/bin/bash\n\n# Install Kaggle CLI\npip install kaggle\n\n# Set your Kaggle API credentials\nexport KAGGLE_USERNAME="jacobukokobili" #$(jq -r \'.username\' ~/.kaggle/kaggle.json)\nexport KAGGLE_KEY="61b5f532a19d8c9f03d309e9b75a02ff" #$(jq -r \'.key\' ~/.kaggle/kaggle.json)\n\n# Download the dataset using Kaggle API and unzip into the /opt/***/etl directory\nkaggle datasets download -d jacksoncrow/stock-market-dataset --unzip -p /opt/***/load']
[2023-05-10 03:55:49,096] {subprocess.py:85} INFO - Output:
[2023-05-10 03:55:52,946] {subprocess.py:89} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-05-10 03:55:54,337] {subprocess.py:89} INFO - Collecting kaggle
[2023-05-10 03:55:55,059] {subprocess.py:89} INFO -   Downloading kaggle-1.5.13.tar.gz (63 kB)
[2023-05-10 03:55:55,366] {subprocess.py:89} INFO -   Preparing metadata (setup.py): started
[2023-05-10 03:55:58,449] {subprocess.py:89} INFO -   Preparing metadata (setup.py): finished with status 'done'
[2023-05-10 03:55:58,457] {subprocess.py:89} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.16.0)
[2023-05-10 03:55:58,458] {subprocess.py:89} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2020.12.5)
[2023-05-10 03:55:58,458] {subprocess.py:89} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.8.2)
[2023-05-10 03:55:58,459] {subprocess.py:89} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.26.0)
[2023-05-10 03:55:59,274] {subprocess.py:89} INFO - Collecting tqdm
[2023-05-10 03:55:59,422] {subprocess.py:89} INFO -   Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
[2023-05-10 03:55:59,494] {subprocess.py:89} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.7/site-packages (from kaggle) (4.0.1)
[2023-05-10 03:55:59,495] {subprocess.py:89} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.26.7)
[2023-05-10 03:55:59,524] {subprocess.py:89} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.7/site-packages (from python-slugify->kaggle) (1.3)
[2023-05-10 03:55:59,587] {subprocess.py:89} INFO - Requirement already satisfied: charset-normalizer~=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (2.0.9)
[2023-05-10 03:55:59,598] {subprocess.py:89} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (3.3)
[2023-05-10 03:55:59,692] {subprocess.py:89} INFO - Building wheels for collected packages: kaggle
[2023-05-10 03:55:59,693] {subprocess.py:89} INFO -   Building wheel for kaggle (setup.py): started
[2023-05-10 03:56:02,832] {subprocess.py:89} INFO -   Building wheel for kaggle (setup.py): finished with status 'done'
[2023-05-10 03:56:02,834] {subprocess.py:89} INFO -   Created wheel for kaggle: filename=kaggle-1.5.13-py3-none-any.whl size=77734 sha256=db5b78928559dde4d47251f5d0e5bbc2c003678850cd15ad0eda51c3d47168f6
[2023-05-10 03:56:02,835] {subprocess.py:89} INFO -   Stored in directory: /home/***/.cache/pip/wheels/fd/97/a6/3372cb23468915cbcf108338dd29c73379fd1a55828ec608ba
[2023-05-10 03:56:02,857] {subprocess.py:89} INFO - Successfully built kaggle
[2023-05-10 03:56:25,484] {subprocess.py:89} INFO - Installing collected packages: tqdm, kaggle
[2023-05-10 03:56:26,944] {subprocess.py:89} INFO - Successfully installed kaggle-1.5.13 tqdm-4.65.0
[2023-05-10 03:56:29,119] {subprocess.py:89} INFO - WARNING: You are using pip version 21.3.1; however, version 23.1.2 is available.
[2023-05-10 03:56:29,119] {subprocess.py:89} INFO - You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[2023-05-10 03:56:32,762] {subprocess.py:89} INFO - stock-market-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)
[2023-05-10 03:56:33,215] {subprocess.py:93} INFO - Command exited with return code 0
[2023-05-10 03:56:33,601] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_processing_dag, task_id=download_dataset, execution_date=20230509T062148, start_date=20230510T035548, end_date=20230510T035633
[2023-05-10 03:56:33,931] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-05-10 03:56:34,338] {local_task_job.py:264} INFO - 2 downstream tasks scheduled from follow-on schedule check
