[2023-05-10 03:56:44,090] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_processing_dag.download_dataset manual__2023-05-10T03:55:45.360950+00:00 [queued]>
[2023-05-10 03:56:44,198] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_processing_dag.download_dataset manual__2023-05-10T03:55:45.360950+00:00 [queued]>
[2023-05-10 03:56:44,198] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 03:56:44,198] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-05-10 03:56:44,199] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 03:56:44,327] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset> on 2023-05-10 03:55:45.360950+00:00
[2023-05-10 03:56:44,344] {standard_task_runner.py:52} INFO - Started process 1423 to run task
[2023-05-10 03:56:44,362] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_processing_dag', 'download_dataset', 'manual__2023-05-10T03:55:45.360950+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/data_processing_dag.py', '--cfg-path', '/tmp/tmpbsg2uswe', '--error-file', '/tmp/tmpmyzp9e8s']
[2023-05-10 03:56:44,363] {standard_task_runner.py:77} INFO - Job 120: Subtask download_dataset
[2023-05-10 03:56:44,654] {logging_mixin.py:109} INFO - Running <TaskInstance: data_processing_dag.download_dataset manual__2023-05-10T03:55:45.360950+00:00 [running]> on host cd79de2e36bd
[2023-05-10 03:56:45,009] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_processing_dag
AIRFLOW_CTX_TASK_ID=download_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-05-10T03:55:45.360950+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-10T03:55:45.360950+00:00
[2023-05-10 03:56:45,023] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-10 03:56:45,024] {subprocess.py:74} INFO - Running command: ['bash', '-c', '#!/bin/bash\n\n# Install Kaggle CLI\npip install kaggle\n\n# Set your Kaggle API credentials\nexport KAGGLE_USERNAME="jacobukokobili" #$(jq -r \'.username\' ~/.kaggle/kaggle.json)\nexport KAGGLE_KEY="61b5f532a19d8c9f03d309e9b75a02ff" #$(jq -r \'.key\' ~/.kaggle/kaggle.json)\n\n# Download the dataset using Kaggle API and unzip into the /opt/***/etl directory\nkaggle datasets download -d jacksoncrow/stock-market-dataset --unzip -p /opt/***/load']
[2023-05-10 03:56:45,082] {subprocess.py:85} INFO - Output:
[2023-05-10 03:56:50,877] {subprocess.py:89} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-05-10 03:56:51,757] {subprocess.py:89} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.7/site-packages (1.5.13)
[2023-05-10 03:56:51,864] {subprocess.py:89} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.26.0)
[2023-05-10 03:56:51,865] {subprocess.py:89} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.7/site-packages (from kaggle) (4.65.0)
[2023-05-10 03:56:51,877] {subprocess.py:89} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2020.12.5)
[2023-05-10 03:56:51,882] {subprocess.py:89} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.16.0)
[2023-05-10 03:56:51,883] {subprocess.py:89} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.8.2)
[2023-05-10 03:56:51,884] {subprocess.py:89} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.26.7)
[2023-05-10 03:56:51,886] {subprocess.py:89} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.7/site-packages (from kaggle) (4.0.1)
[2023-05-10 03:56:52,106] {subprocess.py:89} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.7/site-packages (from python-slugify->kaggle) (1.3)
[2023-05-10 03:56:52,364] {subprocess.py:89} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (3.3)
[2023-05-10 03:56:52,368] {subprocess.py:89} INFO - Requirement already satisfied: charset-normalizer~=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (2.0.9)
[2023-05-10 03:57:42,540] {subprocess.py:89} INFO - WARNING: You are using pip version 21.3.1; however, version 23.1.2 is available.
[2023-05-10 03:57:42,540] {subprocess.py:89} INFO - You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[2023-05-10 03:57:46,673] {subprocess.py:89} INFO - stock-market-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)
[2023-05-10 03:57:46,946] {subprocess.py:93} INFO - Command exited with return code 0
[2023-05-10 03:57:47,083] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_processing_dag, task_id=download_dataset, execution_date=20230510T035545, start_date=20230510T035644, end_date=20230510T035747
[2023-05-10 03:57:47,222] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-05-10 03:57:47,490] {local_task_job.py:264} INFO - 2 downstream tasks scheduled from follow-on schedule check
